config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    resources :rooms, only: [:new, :create]
    resources :bookings, only: [:new, :create, :show]
    resources :reviews, only: [:index, :new, :create]
  end
  resources :rooms, only: [:edit, :update, :destroy]
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :reviews, only: [:edit, :update, :destroy]

  resources :hotel_attachments, only: [:edit, :update, :destroy]
  resources :room_attachments, only: [:edit, :update, :destroy]

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="navbar-wagon footer">
  <br>
  <div class="nav justify-content">
    <a class="nav-link" href="#">Careers</a>
    <a class="nav-link" href="#">Press</a>
    <a class="nav-link" href="#">Policies</a>
    <a class="nav-link" href="#">Help</a>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top navbar-wagon-white ">
  <!-- Logo -->
  <%= link_to image_tag("logo.png", class: "logo"), root_path%>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add a hotel", new_hotel_path, class: "btn btn-outline-primary" %>
      <%= link_to "Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Profile", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <%= image_tag "Jabba_le_Hutt.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>