config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    resources :rooms, only: [:new, :create]
    resources :bookings, only: [:new, :create, :show]
    resources :reviews, only: [:index, :new, :create]
  end
  resources :rooms, only: [:edit, :update, :destroy]
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :reviews, only: [:edit, :update, :destroy]

  resources :hotel_attachments, only: [:edit, :update, :destroy]
  resources :room_attachments, only: [:edit, :update, :destroy]

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  validates :booked, inclusion: { in: ["true", "false"]}
  validates :price, presence: true
  validates :capacity, presence: true, inclusion: { in: [1, 2, 3, 4]}
  validates :category, presence: true
  belongs_to :hotel
  has_many :room_attachments, dependent: :destroy
  accepts_nested_attributes_for :room_attachments
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

skip_before_action :authenticate_user!, only: [:show]
before_action :set_hotel, only: [:index, :new, :create]
before_action :set_room, only: [:edit, :update, :destroy]

  def index
    @hotel = @room.hotel
    @rooms = Room.where(hotel: @hotel)
  end

  def show
    @room_attachments = @room.room_attachments.all
    authorize @room
  end

  def new
    @room = Room.new
    @room.hotel = @hotel
    @room_attachment = @room.room_attachments.build
    authorize @room
  end

  def create
    @room = Room.new(room_params)
    @room.hotel = @hotel
    if @room.save
      if params[:room_attachments] != nil
      params[:room_attachments]['photo'].each do |a|
        @room_attachment = @room.room_attachments.create!(:photo => a)
      end
      redirect_to hotel_path(@hotel)
    else
      redirect_to hotel_path(@hotel)
    end
    else
      render :new
    end
    authorize @room
  end

  def edit
    authorize @room
  end

  def update
    @hotel =  @room.hotel
    @room.update(room_params)
    redirect_to hotel_path(@hotel), notice: 'Room was successfully updated.'
    authorize @room
  end

  def destroy
    @hotel =  @room.hotel
    @room.destroy
    redirect_to hotel_path(@hotel), notice: 'Room was successfully destroyed.'
    authorize @room
  end

  private

  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:price, :capacity, :category, room_attachments_attributes: [:id, :room_id, :photo])
  end
end

app/views/rooms/_edit.html.erb
<%= simple_form_for [@hotel, @room] do |f| %>
  <%= f.input :category %>
  <%= f.input :capacity %>
  <%= f.input :price %>
  <%= f.fields_for :room_attachments do |p| %>
    <%= p.label :photo %>
    <%= p.file_field :photo, :multiple => true, name: "room_attachments[photo][]" %>
    <% end %>
  <%= f.button :submit %>
<% end %>

app/views/rooms/_index.html.erb
<table class="table table-striped" style="width: 100%">
  <tr>
    <th scope="col">Category</th>
    <th scope="col">Capacity</th>
    <th scope="col">Price</th>
  </tr>
  <tr>
        <% @hotel.rooms.each do |room| %>
           <td><%= room.category %></td>
           <td><%= room.capacity %></td>
           <td><%= room.price %>DH</td>
            <%if policy(room).edit? %>
            <td> <%= link_to "Edit", edit_room_path(room) %></td>
            <% end %>
            <%if policy(room).destroy? %>
              <td><%= link_to "Delete", room_path(room), method: :delete, data: { confirm: "Are you sure?" } %></td>
            <% end %>
  </tr>
  <% end %>
</table>
            <% @hotel.rooms.each do |room| %>
            <% room.room_attachments.each do |p| %>
              <%= image_tag p.photo_url %>
              <%= link_to "Edit Attachment", edit_room_attachment_path(p) %>
              <% if policy(p).destroy? %>
                <%= link_to "delete Attachment", room_attachment_path(p),method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            <% end %>
        <% end %>

app/views/rooms/edit.html.erb
<%= simple_form_for [@hotel, @room] do |f| %>
  <%= f.input :category %>
  <%= f.input :capacity %>
  <%= f.input :price %>
  <%= f.fields_for :room_attachments do |p| %>
    <%= p.label :photo %>
    <%= p.file_field :photo, :multiple => true, name: "room_attachments[photo][]" %>
    <% end %>
  <%= f.button :submit %>
<% end %>

app/views/rooms/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h3 class="text-center"> Add a new room to your hotel </h3>
      <%= simple_form_for [@hotel, @room], :html => { :multipart => true } do |f| %>
        <%= f.input :category %>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <%= f.fields_for :room_attachments do |p| %>
          <%= p.label :photo %>
          <%= p.file_field :photo, :multiple => true, name: "room_attachments[photo][]" %>
          <% end %>
        <br>
        <%= f.button :submit, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</div>