config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    resources :rooms, only: [:new, :create]
    resources :bookings, only: [:new, :create, :show]
    resources :reviews, only: [:index, :new, :create]
  end
  resources :rooms, only: [:edit, :update, :destroy]
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :reviews, only: [:edit, :update, :destroy]

  resources :hotel_attachments, only: [:edit, :update, :destroy]
  resources :room_attachments, only: [:edit, :update, :destroy]

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true
  has_many :rooms, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookings, through: :rooms
  has_many :hotel_attachments, dependent: :destroy
  accepts_nested_attributes_for :hotel_attachments
  belongs_to :user
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:city].present?
        @hotels = Hotel.near(params[:city],50)
      else
        @hotels = Hotel.all
    end
    cookies[:arriving_date] = params[:arriving_date]
    cookies[:departing_date] = params[:departing_date]
  end

  def show
    @hotel = Hotel.find(params[:id])
    @hotel_attachments = @hotel.hotel_attachments.all

   # @bookings = Booking.where("arriving_date >= ? AND departing_date <= ?")

    @markers =
      [{
        lat: @hotel.latitude,
        lng: @hotel.longitude,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }]
    authorize @hotel
  end

  def new
    @hotel = Hotel.new
    @hotel_attachment = @hotel.hotel_attachments.build
    authorize @hotel
  end

  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.user = current_user
    if @hotel.save
      if params[:hotel_attachments] != nil
      params[:hotel_attachments]['photo'].each do |a|
        @hotel_attachment = @hotel.hotel_attachments.create!(:photo => a)
      end
      redirect_to hotel_path(@hotel)
    else
      redirect_to hotel_path(@hotel)
    end
    else
      render :new
    end
    authorize @hotel
  end

  def edit
    authorize @hotel
  end

  def update
    @hotel.update(hotel_params)
    redirect_to hotel_path(@hotel)
    authorize @hotel
  end

  def destroy
    @hotel.destroy
    redirect_to hotels_path
    authorize @hotel
  end

  private

  def hotel_params
    params.require(:hotel).permit(:name, :address, :stars, hotel_attachments_attributes: [:id, :hotel_id, :photo])
  end

  def set_hotel
    @hotel = Hotel.find(params[:id])
  end
end

app/views/hotels/_carousel.html.erb
<% unless @hotel_attachments.empty? %>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="item active" style="height: 400px">
        <%= image_tag(@hotel_attachments.first.photo_url) %>
      </div>
      <% @hotel_attachments.drop(1).each do |p| %>
      <div class="item" style="height: 400px">
        <%= image_tag(p.photo_url) %>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/hotels/_form.html.erb
<%= simple_form_for @hotel, :html => { :multipart => true } do |f| %>
  <%= f.input :name %>
  <%= f.input :address, input_html: {id: "flat_address"} %>
  <%= f.input :stars, collection: (0..5) %>
  <%= f.fields_for :hotel_attachments do |p| %>
    <%= p.label :photo %>
    <%= p.file_field :photo, :multiple => true, name: "hotel_attachments[photo][]" %>
    <% end %>
    <br/>
  <%= f.button :submit, class: "btn btn-success" %>
<% end %>
<br>

app/views/hotels/edit.html.erb
<%= render 'form' %>
<%= link_to 'Home', hotels_path %>

app/views/hotels/index.html.erb
<div class="container-dates">
  <%= form_tag hotels_path, method: :get do %>
      <%= text_field_tag :city, params[:city], class: "form-control", placeholder: "Find a city",value: @city, id: "flat_address"%>
      <%= date_field(:departing_date, params[:departing_date],value: cookies[:departing_date], class: "form-control") %>
      <%= date_field(:arriving_date, params[:arriving_date],value: cookies[:arriving_date], class: "form-control") %>

     <%= submit_tag("Search", class: "btn btn-success") %>
    <% end %>
  </div
</div>
<div class="container-hotel">
   <div class="row">
    <h1 class="text-center">Hotels</h1>
    <% @hotels.each do |hotel| %>
    <div class="col-xs-12">
      <div class="card-hotel">
        <%= link_to "", hotel_path(hotel), class: "card-link" %>
        <div class="row">
          <div class="col-xs-5">
        <% if hotel.hotel_attachments.first != nil %>
          <%= image_tag hotel.hotel_attachments.first.photo_url,height: 175, class: "card-photo" %>
        <% end %>
        </div>
        <div class="col-xs-offset-1 col-xs-6">
        <div class="card-body">
          <h2><%= hotel.name %></h2>
          <h3><%= hotel.stars %> Stars</h3>
        </div>
        </div>
      </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/hotels/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h1> Add your hotel to our platform </h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/hotels/show.html.erb
<div class="main-container">
  <div class="container">
      <h3><%= @hotel.name %></h3>
        <%= @hotel.address %><br>
        <% if policy(@hotel).update? %>
          <%= link_to "Edit", edit_hotel_path(@hotel) %>
          <%= link_to "Delete", hotel_path(@hotel), method: :delete, data: {confirm: "Are you sure?"} %>
        <% end %>
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
      <%= render 'carousel' %>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div id="map" style="width: 100%; position: relative; overflow: hidden;" data-markers="<%= @markers.to_json %>">
          </div>
        </div>
      </div>
      <br>
      <% if policy(@hotel).update? %>
      <%= link_to "Add a room", new_hotel_room_path(@hotel) %>
      <% end %>
      <%= render '/rooms/index' %>
      <br>
    <div class="list" >
      <%= link_to "Book this hotel", new_hotel_booking_path(@hotel), class: "btn btn-success" %>
    </div>
      <%= render '/reviews/index' %>
      </div>
    </div>
  </div>
</div>