config/routes.rb
Rails.application.routes.draw do
  resources :hotels do
    resources :rooms, only: [:new, :create]
    resources :bookings, only: [:new, :create, :show]
    resources :reviews, only: [:index, :new, :create]
  end
  resources :rooms, only: [:edit, :update, :destroy]
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :reviews, only: [:edit, :update, :destroy]

  resources :hotel_attachments, only: [:edit, :update, :destroy]
  resources :room_attachments, only: [:edit, :update, :destroy]

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_hotel, only: [:show, :index, :new, :create]
  before_action :set_review, only:[:edit, :update, :destroy]
  def index
    @reviews = Review.all
  end

  def show
    authorize @review
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.hotel = @hotel
    if @review.save
      redirect_to hotel_path(@hotel)
    else
      render 'new'
    end
    authorize @review
  end

  def edit
    authorize @review
  end

  def update
    @review.update(review_params)
    redirect_to hotel_path(@hotel)
    authorize @review
  end

  def destroy
    @review.destroy
    redirect_to hotel_path
    authorize @review
  end

  private

  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def set_review
    @review = Review.find(params[:review_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/views/reviews/_form.html.erb
<%= simple_form_for [@hotel, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5], prompt: 'rate the hotel' %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/_index.html.erb
<h3>Reviews:</h3>
<ul class="list-unstyled">
  <% @hotel.reviews.each do |review| %>
  <li class='padded-1em'>
    <%= review.content %>
    <%= review.rating %> / 5
  </li>
<% end %>
</ul>
  <%= link_to 'Add a review', new_hotel_review_path(@hotel) %>

app/views/reviews/edit.html.erb
<%= render 'form' %>
<%= link_to 'Home', hotels_path %>

app/views/reviews/new.html.erb
<%= render 'form' %>
<%= link_to 'Home', hotels_path %>

app/views/reviews/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1 class="text-center">100% <strong>Verified</strong> Reviews</h1>
      <%= review.rating %>
      <%= review.content %>
      <%= link_to 'Home', hotels_path %>
    </div>
  </div>
</div>